[package]
name = "main"
version = "0.1.0"
edition = "2024"

[dependencies]
eyre               = "0.6.12"
tracing            = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
rustls             = "0.23.5"
